---
PRINT_ALL_FILES: false
DISABLE_LINTERS:
  - SPELL_CSPELL
  - YAML_PRETTIER
  - REPOSITORY_SEMGREP
  - REPOSITORY_TRIVY
  - REPOSITORY_CHECKOV
  - REPOSITORY_GITLEAKS
  - COPYPASTE_JSCPD
SPELL_MISSPELL_DISABLE_ERRORS: false
PARALLEL: true
