blank_issues_enabled: true
contact_links:
  - name: 🗣 Subproject discussions
    url: https://github.com/camaraproject/QualityOnDemand/discussions
    about: Please ask and answer questions here.
  - name: 📖 CAMARA API Design Guidelines
    url: https://github.com/camaraproject/Commonalities/blob/main/documentation/CAMARA-API-Design-Guide.md
    about: Please refer to the design guidelines.
